### ISSUE TITLE
PacBioEntity is missing a constructor

### ISSUE THREAD

**Issue by kjsanger** [wtsi-npg/npg_id_generation#18]
https://github.com/wtsi-npg/npg_id_generation/blob/b7a2da5629a9738c1aa533d2792b243fd014c9bd/npg_id_generation/pac_bio.py#L46

This class doesn't have a constructor, which makes creating one awkward and also means there's no docstring.

**Comment by nerdstrike** [comment]
PacBioEntity inherits a constructor from `BaseModel` and does not need one. Docstrings for pydantic classes are very much up for debate.
